<?php

namespace App\Services\Jobs;

use App\Models\Job;

/**
 * Builds a small, dependency-free PDF so completed reports work on every
 * deployment without requiring a separate PDF runtime or binary.
 *
 * The report contains the complete audit trail and a photo index. Photos stay
 * in their existing protected storage and are linked back to the in-app photo
 * endpoint, so the report never exposes an unprotected bucket URL.
 */
class JobCompletionReportPdfGenerator
{
    private const WIDTH = 595.28;
    private const HEIGHT = 841.89;
    private const LEFT = 52;
    private const TOP = 790;
    private const BOTTOM = 52;

    public function render(Job $job): string
    {
        $lines = $this->buildLines($job);
        $pages = array_chunk($lines, 42);
        $pageOperations = [];

        foreach ($pages as $index => $pageLines) {
            $ops = [];
            $this->drawRect($ops, 0, self::HEIGHT - 86, self::WIDTH, 86, [11 / 255, 93 / 255, 71 / 255]);
            $this->text($ops, 'MotorRelay', self::LEFT, self::HEIGHT - 42, 24, true, [1, 1, 1]);
            $this->text($ops, 'COMPLETION REPORT', self::WIDTH - 190, self::HEIGHT - 40, 12, true, [1, 1, 1]);
            $this->text($ops, sprintf('Job #%d  •  Page %d of %d', $job->id, $index + 1, count($pages)), self::LEFT, self::HEIGHT - 105, 10, true, [11 / 255, 93 / 255, 71 / 255]);

            $y = self::TOP - 30;
            foreach ($pageLines as $line) {
                $this->text($ops, $line, self::LEFT, $y, 9.5, false, [48 / 255, 51 / 255, 58 / 255]);
                $y -= 16;
            }

            $this->drawLine($ops, self::LEFT, 34, self::WIDTH - self::LEFT, 34, [0.82, 0.85, 0.87], 0.6);
            $this->text($ops, 'Generated by MotorRelay', self::LEFT, 20, 8, false, [90 / 255, 95 / 255, 105 / 255]);
            $pageOperations[] = $ops;
        }

        return $this->finalizePdf($pageOperations);
    }

    private function buildLines(Job $job): array
    {
        $lines = [
            'JOB SUMMARY',
            'Registration / title: ' . ($job->title ?: 'Not provided'),
            'Vehicle: ' . trim(($job->vehicle_make ?: 'Not provided') . ' ' . ($job->vehicle_type ?: '')),
            'Status: ' . $this->label($job->status) . '  |  Completion: ' . $this->label($job->completion_status),
            'Listing: ' . $this->label($job->listing_type) . ($job->auction_reference ? '  |  Auction reference: ' . $job->auction_reference : ''),
            '',
            'PARTICIPANTS',
            'Dealer: ' . $this->person($job->postedBy),
            'Driver: ' . ($job->assignedTo ? $this->person($job->assignedTo) : 'Not assigned'),
            '',
            'ROUTE AND TIMINGS',
            'Pickup: ' . $this->route($job->pickup_label, $job->pickup_postcode),
            'Drop-off: ' . $this->route($job->dropoff_label, $job->dropoff_postcode),
            'Pickup ready: ' . $this->date($job->pickup_ready_at),
            'Delivery due: ' . $this->date($job->delivery_due_at),
            'Distance: ' . ($job->distance_mi !== null ? $job->distance_mi . ' miles' : 'Not recorded'),
            'Transport: ' . $this->label($job->transport_type),
            '',
            'PAYMENT',
            'Dealer charge: £' . number_format((float) $job->price, 2),
            'Platform fee: £' . number_format((float) $job->platform_fee_amount, 2),
            'Driver payout: £' . number_format((float) $job->driver_payout_amount, 2),
            'Payment status: ' . $this->label($job->payment_status),
            'Paid at: ' . $this->date($job->paid_at),
            'Payout released: ' . $this->date($job->payout_released_at),
            '',
            'COMPLETION TIMELINE',
            'Assigned: ' . $this->date($job->assigned_at),
            'Inspection / completion submitted: ' . $this->date($job->completion_submitted_at),
            'Completion approved: ' . $this->date($job->completion_approved_at),
            'Completed: ' . $this->date($job->completed_at),
            'Completion notes: ' . ($job->completion_notes ?: 'None'),
            'Job notes: ' . ($job->notes ?: 'None'),
            '',
            'INSPECTION PHOTOS',
            'Photos uploaded: ' . $job->inspectionPhotos->count(),
        ];

        foreach ($job->inspectionPhotos as $photo) {
            $lines[] = sprintf('Photo %d: %s (%s)  •  In-app path: /jobs/%d/inspection-photos/%d', $photo->sort_order ?: $photo->id, $photo->original_name ?: 'Unnamed photo', $this->date($photo->created_at), $job->id, $photo->id);
        }

        if ($job->auction_assessment_report_name) {
            $lines[] = 'Assessment report: ' . $job->auction_assessment_report_name;
        }

        $lines[] = '';
        $lines[] = 'ISSUES, RECOVERY AND EXPENSES';
        if ($job->incidents->isEmpty()) {
            $lines[] = 'Issues reported: None';
        } else {
            foreach ($job->incidents as $incident) {
                $lines[] = sprintf('%s: %s (%s) — %s', $this->label($incident->type), $this->label($incident->status), $this->date($incident->created_at), $incident->description ?: 'No description');
                $lines[] = '  Recovery: ' . ($incident->recovery_required ? ($incident->recovery_completed_at ? 'Completed' : 'Required') : 'Not required');
            }
        }

        if ($job->expenses->isEmpty()) {
            $lines[] = 'Expenses: None';
        } else {
            foreach ($job->expenses as $expense) {
                $lines[] = sprintf('Expense: £%s — %s (%s)', number_format((float) $expense->total_amount, 2), $expense->description, $this->label($expense->status));
            }
        }

        $lines[] = '';
        $lines[] = 'TRACKING';
        $lines[] = 'Last known location: ' . ($job->current_latitude !== null && $job->current_longitude !== null ? $job->current_latitude . ', ' . $job->current_longitude : 'Not recorded');
        $lines[] = 'Last location update: ' . $this->date($job->last_tracked_at);
        $lines[] = 'This report is an audit record. Inspection images remain available to authorised users in MotorRelay.';

        return $this->wrapLines($lines);
    }

    private function wrapLines(array $lines): array
    {
        $wrapped = [];
        foreach ($lines as $line) {
            if ($line === '') { $wrapped[] = ''; continue; }
            foreach (str_split($line, 92) as $part) { $wrapped[] = $part; }
        }
        return $wrapped;
    }

    private function person($user): string
    {
        if (! $user) {
            return 'Unknown';
        }

        return trim(($user->name ?? 'Unknown') . ($user->email ? ' <' . $user->email . '>' : ''));
    }

    private function route(?string $label, ?string $postcode): string
    {
        return trim(($label ?: 'Not provided') . ($postcode ? ' (' . $postcode . ')' : ''));
    }

    private function date($value): string
    {
        return $value ? $value->format('d M Y H:i') : 'Not recorded';
    }

    private function label(?string $value): string
    {
        return ucwords(str_replace(['_', '-'], ' ', (string) ($value ?: 'Not recorded')));
    }

    private function text(array &$ops, string $value, float $x, float $y, float $size, bool $bold, array $rgb): void
    {
        $ops[] = sprintf(
            '%.3f %.3f %.3f rg BT /%s %.2f Tf 1 0 0 1 %.2f %.2f Tm (%s) Tj ET',
            $rgb[0], $rgb[1], $rgb[2], $bold ? 'F2' : 'F1', $size, $x, $y, $this->escape($value)
        );
    }

    private function drawRect(array &$ops, float $x, float $y, float $width, float $height, array $rgb): void
    {
        $ops[] = sprintf('q %.3f %.3f %.3f rg %.2f %.2f %.2f %.2f re f Q', $rgb[0], $rgb[1], $rgb[2], $x, $y, $width, $height);
    }

    private function drawLine(array &$ops, float $x1, float $y1, float $x2, float $y2, array $rgb, float $width): void
    {
        $ops[] = sprintf('q %.3f %.3f %.3f RG %.2f w %.2f %.2f m %.2f %.2f l S Q', $rgb[0], $rgb[1], $rgb[2], $width, $x1, $y1, $x2, $y2);
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', '(', ')', "\r", "\n"], ['\\\\', '\\(', '\\)', ' ', ' '], iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $value) ?: $value);
    }

    private function finalizePdf(array $pages): string
    {
        $objects = ["1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj", '2 0 obj << /Type /Pages /Kids [] /Count 0 >> endobj'];
        $pageIds = [];
        foreach ($pages as $operations) {
            $stream = implode("\n", $operations) . "\n";
            $contentId = count($objects) + 1;
            $pageId = $contentId + 1;
            $fontRegular = $pageId + 1;
            $fontBold = $pageId + 2;
            // PDF stream delimiters must contain real line breaks; using a
            // single-quoted PHP string here would emit the literal `\\n` and
            // make readers treat the page content as an empty stream.
            $objects[] = sprintf("%d 0 obj << /Length %d >> stream\n%sendstream endobj", $contentId, strlen($stream), $stream);
            $objects[] = sprintf('%d 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 %.2f %.2f] /Contents %d 0 R /Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> >> >> endobj', $pageId, self::WIDTH, self::HEIGHT, $contentId, $fontRegular, $fontBold);
            $objects[] = sprintf('%d 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj', $fontRegular);
            $objects[] = sprintf('%d 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj', $fontBold);
            $pageIds[] = $pageId;
        }
        $objects[1] = sprintf('2 0 obj << /Type /Pages /Kids [%s] /Count %d >> endobj', implode(' ', array_map(fn ($id) => $id . ' 0 R', $pageIds)), count($pageIds));

        $pdf = "%PDF-1.4\n"; $offsets = [0];
        foreach ($objects as $object) { $offsets[] = strlen($pdf); $pdf .= $object . "\n"; }
        $xref = strlen($pdf); $pdf .= "xref\n0 " . count($offsets) . "\n";
        foreach ($offsets as $offset) { $pdf .= str_pad((string) $offset, 10, '0', STR_PAD_LEFT) . " 00000 n \n"; }
        return $pdf . "trailer << /Size " . count($offsets) . " /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
    }
}
