<?php

namespace App\Services\Jobs;

use App\Models\Job;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

/**
 * Builds a small, dependency-free PDF so completed reports work on every
 * deployment without requiring a separate PDF runtime or binary.
 *
 * The report contains the complete audit trail and an image appendix. JPEG
 * inspection images are embedded in the PDF, so the downloaded report is
 * self-contained and does not depend on a private storage URL expiring.
 */
class JobCompletionReportPdfGenerator
{
    private const WIDTH = 595.28;
    private const HEIGHT = 841.89;
    private const LEFT = 52;
    private const TOP = 790;
    private const BOTTOM = 52;

    public function render(Job $job): string
    {
        $lines = $this->buildLines($job);
        $textPages = array_chunk($lines, 30);
        $photoPages = $job->inspectionPhotos
            ->values()
            ->map(fn ($photo, $index) => $this->buildPhotoPage($job, $photo, $index + 1))
            ->all();
        $totalPages = 1 + count($textPages) + count($photoPages);
        $pageOperations = [];

        // A dedicated cover gives the report the same confident, editorial
        // feel as the MotorRelay product rather than opening on raw data.
        $pageOperations[] = $this->buildCoverPage($job, $totalPages);

        foreach ($textPages as $index => $pageLines) {
            $ops = [];
            $this->drawRect($ops, 0, self::HEIGHT - 86, self::WIDTH, 86, [11 / 255, 93 / 255, 71 / 255]);
            $this->text($ops, 'MotorRelay', self::LEFT, self::HEIGHT - 42, 24, true, [1, 1, 1]);
            $this->text($ops, 'COMPLETION REPORT', self::WIDTH - 190, self::HEIGHT - 40, 12, true, [1, 1, 1]);
            // Keep the marker in the header gutter, separate from report data.
            $this->text($ops, sprintf('Job #%d  •  Page %d of %d', $job->id, $index + 2, $totalPages), self::LEFT, self::HEIGHT - 112, 9.5, true, [11 / 255, 93 / 255, 71 / 255]);

            $y = self::HEIGHT - 146;
            foreach ($pageLines as $line) {
                $heading = $line !== '' && preg_match('/^[A-Z][A-Z &\\/]+$/', $line);
                if ($heading) {
                    $this->drawRect($ops, self::LEFT - 8, $y - 5, self::WIDTH - (self::LEFT * 2) + 16, 19, [232 / 255, 248 / 255, 241 / 255]);
                    $this->text($ops, $line, self::LEFT, $y, 9.5, true, [11 / 255, 125 / 255, 87 / 255]);
                } else {
                    $this->text($ops, $line, self::LEFT, $y, 10, false, [48 / 255, 51 / 255, 58 / 255]);
                }
                $y -= $heading ? 27 : 19;
            }

            $this->drawLine($ops, self::LEFT, 34, self::WIDTH - self::LEFT, 34, [0.82, 0.85, 0.87], 0.6);
            $this->text($ops, 'Generated by MotorRelay', self::LEFT, 20, 8, false, [90 / 255, 95 / 255, 105 / 255]);
            $pageOperations[] = ['operations' => $ops, 'images' => []];
        }

        foreach ($photoPages as $photoPage) {
            $photoPage['operations'][] = sprintf('q 0.91 0.96 0.94 rg %.2f %.2f %.2f %.2f re f Q', self::LEFT - 8, 82, self::WIDTH - (self::LEFT * 2) + 16, 28);
            $this->text($photoPage['operations'], 'Generated by MotorRelay', self::LEFT, 94, 8, false, [11 / 255, 93 / 255, 71 / 255]);
            $pageOperations[] = $photoPage;
        }

        return $this->finalizePdf($pageOperations);
    }

    private function buildCoverPage(Job $job, int $totalPages): array
    {
        $ops = [];
        $green = [11 / 255, 93 / 255, 71 / 255];
        $mint = [94 / 255, 226 / 255, 174 / 255];
        $ink = [3 / 255, 8 / 255, 22 / 255];
        $this->drawRect($ops, 0, 0, self::WIDTH, self::HEIGHT, [248 / 255, 251 / 255, 250 / 255]);
        $this->drawRect($ops, 0, self::HEIGHT - 270, self::WIDTH, 270, $ink);
        $this->drawRect($ops, self::LEFT, self::HEIGHT - 110, 72, 4, $mint);
        $this->text($ops, 'MotorRelay', self::LEFT, self::HEIGHT - 72, 27, true, [1, 1, 1]);
        $this->text($ops, 'COMPLETION REPORT', self::LEFT, self::HEIGHT - 165, 12, true, $mint);
        $this->text($ops, 'A complete record of this vehicle movement', self::LEFT, self::HEIGHT - 205, 13, false, [225 / 255, 235 / 255, 233 / 255]);

        $plate = strtoupper($job->title ?: 'MOTORRELAY JOB');
        $this->drawRect($ops, self::LEFT, 440, self::WIDTH - (self::LEFT * 2), 125, [1, 1, 1]);
        $this->text($ops, 'VEHICLE', self::LEFT + 20, 535, 10, true, $green);
        $this->text($ops, $plate, self::LEFT + 20, 488, 30, true, $ink);
        $this->text($ops, trim(($job->vehicle_make ?: '') . ' ' . ($job->vehicle_type ?: '')), self::LEFT + 22, 462, 11, false, [90 / 255, 95 / 255, 105 / 255]);
        $this->drawRect($ops, self::LEFT, 350, self::WIDTH - (self::LEFT * 2), 60, [232 / 255, 248 / 255, 241 / 255]);
        $this->text($ops, $this->label($job->status), self::LEFT + 20, 374, 13, true, $green);
        $this->text($ops, 'COMPLETED MOVEMENT', self::WIDTH - 190, 374, 9, true, $green);

        $this->text($ops, 'ROUTE', self::LEFT, 290, 10, true, $green);
        $this->text($ops, $this->shorten($job->pickup_label ?: $job->pickup_postcode ?: 'Pickup'), self::LEFT, 260, 12, true, $ink);
        $this->drawRect($ops, self::LEFT, 228, 30, 18, $green);
        $this->text($ops, 'TO', self::LEFT + 7, 234, 7.5, true, [1, 1, 1]);
        $this->text($ops, $this->shorten($job->dropoff_label ?: $job->dropoff_postcode ?: 'Drop-off'), self::LEFT, 205, 12, true, $ink);
        $this->drawLine($ops, self::LEFT, 145, self::WIDTH - self::LEFT, 145, [210 / 255, 220 / 255, 219 / 255], 0.7);
        $this->text($ops, 'Generated by MotorRelay  •  motorrelay.com', self::LEFT, 112, 9, false, [90 / 255, 95 / 255, 105 / 255]);
        $this->text($ops, sprintf('Job #%d  •  %d pages', $job->id, $totalPages), self::LEFT, 92, 9, false, [90 / 255, 95 / 255, 105 / 255]);
        return ['operations' => $ops, 'images' => []];
    }

    private function shorten(?string $value): string
    {
        $value = trim((string) $value);
        return strlen($value) > 66 ? substr($value, 0, 63) . '...' : ($value ?: 'Not provided');
    }

    private function buildLines(Job $job): array
    {
        $lines = [
            'JOB SUMMARY',
            'Registration / title: ' . ($job->title ?: 'Not provided'),
            'Vehicle: ' . trim(($job->vehicle_make ?: 'Not provided') . ' ' . ($job->vehicle_type ?: '')),
            'Status: ' . $this->label($job->status) . '  |  Completion: ' . $this->label($job->completion_status),
            'Listing: ' . $this->label($job->listing_type) . ($job->auction_reference ? '  |  Auction reference: ' . $job->auction_reference : ''),
            '',
            'PARTICIPANTS',
            'Dealer: ' . $this->person($job->postedBy),
            'Driver: ' . ($job->assignedTo ? $this->person($job->assignedTo) : 'Not assigned'),
            '',
            'ROUTE AND TIMINGS',
            'Pickup: ' . $this->route($job->pickup_label, $job->pickup_postcode),
            'Drop-off: ' . $this->route($job->dropoff_label, $job->dropoff_postcode),
            'Pickup ready: ' . $this->date($job->pickup_ready_at),
            'Delivery due: ' . $this->date($job->delivery_due_at),
            'Distance: ' . ($job->distance_mi !== null ? $job->distance_mi . ' miles' : 'Not recorded'),
            'Transport: ' . $this->label($job->transport_type),
            '',
            'PAYMENT',
            'Dealer charge: £' . number_format((float) $job->price, 2),
            'Platform fee: £' . number_format((float) $job->platform_fee_amount, 2),
            'Driver payout: £' . number_format((float) $job->driver_payout_amount, 2),
            'Payment status: ' . $this->label($job->payment_status),
            'Paid at: ' . $this->date($job->paid_at),
            'Payout released: ' . $this->date($job->payout_released_at),
            '',
            'COMPLETION TIMELINE',
            'Assigned: ' . $this->date($job->assigned_at),
            'Inspection / completion submitted: ' . $this->date($job->completion_submitted_at),
            'Completion approved: ' . $this->date($job->completion_approved_at),
            'Completed: ' . $this->date($job->completed_at),
            'Completion notes: ' . ($job->completion_notes ?: 'None'),
            'Job notes: ' . ($job->notes ?: 'None'),
            '',
            'INSPECTION PHOTOS',
            'Photos uploaded: ' . $job->inspectionPhotos->count(),
        ];

        foreach ($job->inspectionPhotos as $photo) {
            $lines[] = sprintf('Photo %d  •  Uploaded %s  •  Included in the photo appendix', $photo->sort_order ?: $photo->id, $this->date($photo->created_at));
        }

        if ($job->auction_assessment_report_name) {
            $lines[] = 'Assessment report: ' . $job->auction_assessment_report_name;
        }

        $lines[] = '';
        $lines[] = 'ISSUES, RECOVERY AND EXPENSES';
        if ($job->incidents->isEmpty()) {
            $lines[] = 'Issues reported: None';
        } else {
            foreach ($job->incidents as $incident) {
                $lines[] = sprintf('%s: %s (%s) — %s', $this->label($incident->type), $this->label($incident->status), $this->date($incident->created_at), $incident->description ?: 'No description');
                $lines[] = '  Recovery: ' . ($incident->recovery_required ? ($incident->recovery_completed_at ? 'Completed' : 'Required') : 'Not required');
            }
        }

        if ($job->expenses->isEmpty()) {
            $lines[] = 'Expenses: None';
        } else {
            foreach ($job->expenses as $expense) {
                $lines[] = sprintf('Expense: £%s — %s (%s)', number_format((float) $expense->total_amount, 2), $expense->description, $this->label($expense->status));
            }
        }

        $lines[] = '';
        $lines[] = 'TRACKING';
        $lines[] = 'Last known location: ' . ($job->current_latitude !== null && $job->current_longitude !== null ? $job->current_latitude . ', ' . $job->current_longitude : 'Not recorded');
        $lines[] = 'Last location update: ' . $this->date($job->last_tracked_at);
        $lines[] = 'This report is an audit record. Inspection images remain available to authorised users in MotorRelay.';

        return $this->wrapLines($lines);
    }

    private function wrapLines(array $lines): array
    {
        $wrapped = [];
        foreach ($lines as $line) {
            if ($line === '') { $wrapped[] = ''; continue; }
            foreach (str_split($line, 92) as $part) { $wrapped[] = $part; }
        }
        return $wrapped;
    }

    /** Build a branded appendix page and embed its JPEG when available. */
    private function buildPhotoPage(Job $job, $photo, int $number): array
    {
        $ops = [];
        $this->drawRect($ops, 0, self::HEIGHT - 86, self::WIDTH, 86, [3 / 255, 8 / 255, 22 / 255]);
        $this->text($ops, 'MotorRelay', self::LEFT, self::HEIGHT - 42, 24, true, [1, 1, 1]);
        $this->text($ops, 'INSPECTION GALLERY', self::WIDTH - 205, self::HEIGHT - 40, 11, true, [94 / 255, 226 / 255, 174 / 255]);
        $this->text($ops, sprintf('Job #%d  •  Photo %d of %d', $job->id, $number, $job->inspectionPhotos->count()), self::LEFT, self::HEIGHT - 115, 12, true, [11 / 255, 125 / 255, 87 / 255]);
        $this->drawRect($ops, self::LEFT - 8, 145, self::WIDTH - (self::LEFT * 2) + 16, 570, [246 / 255, 249 / 255, 250 / 255]);

        $image = $this->loadJpeg($photo);
        if ($image) {
            $rotated = in_array($image['orientation'], [5, 6, 7, 8], true);
            $displayWidth = $rotated ? $image['height'] : $image['width'];
            $displayHeight = $rotated ? $image['width'] : $image['height'];
            $scale = min((self::WIDTH - 100) / $displayWidth, 510 / $displayHeight);
            $width = $displayWidth * $scale;
            $height = $displayHeight * $scale;
            $x = (self::WIDTH - $width) / 2;
            $y = 430 - ($height / 2);
            $ops[] = $this->imagePlacement($image, $scale, $x, $y);
            $images = [$image];
        } else {
            $this->text($ops, 'Preview unavailable', self::LEFT + 30, 430, 18, true, [48 / 255, 51 / 255, 58 / 255]);
            $this->text($ops, 'View this image in MotorRelay.', self::LEFT + 30, 400, 10, false, [90 / 255, 95 / 255, 105 / 255]);
            $images = [];
        }

        $this->text($ops, 'INSPECTION PHOTO', self::LEFT, 115, 10, true, [11 / 255, 125 / 255, 87 / 255]);
        $this->text($ops, 'Uploaded ' . $this->date($photo->created_at), self::LEFT, 99, 9.5, false, [90 / 255, 95 / 255, 105 / 255]);
        return ['operations' => $ops, 'images' => $images];
    }

    private function loadJpeg($photo): ?array
    {
        try {
            // Inspection uploads use their own disk (usually S3/receipts),
            // which can differ from the app's default disk.
            $path = ltrim((string) $photo->path, '/');
            $configuredDisk = $photo->disk ?: config('invoices.proof_disk', config('filesystems.default'));
            $candidateDisks = array_values(array_unique(array_filter([
                $configuredDisk,
                config('invoices.proof_disk'),
                's3',
                config('filesystems.default'),
            ])));
            $storage = null;
            $disk = null;
            foreach ($candidateDisks as $candidateDisk) {
                $candidateStorage = Storage::disk($candidateDisk);
                if ($path !== '' && $candidateStorage->exists($path)) {
                    $storage = $candidateStorage;
                    $disk = $candidateDisk;
                    break;
                }
            }

            if (! $storage || ! $disk) {
                Log::warning('Completion report image not found', ['job_id' => $photo->job_id, 'photo_id' => $photo->id, 'disks_checked' => $candidateDisks, 'path' => $path]);
                return null;
            }
            $bytes = $storage->get($path);
            $info = function_exists('getimagesizefromstring') ? @getimagesizefromstring($bytes) : false;
            if (! $info) {
                Log::warning('Completion report image is unreadable', ['job_id' => $photo->job_id, 'photo_id' => $photo->id, 'disk' => $disk, 'path' => $photo->path, 'mime' => $photo->mime_type]);
                return null;
            }

            // Normalize every source through GD when available. Mobile
            // cameras can upload progressive/CMYK JPEGs or WebP files; those
            // are valid images but are not consistently rendered by PDF
            // viewers when copied directly into a DCTDecode stream.
            $normalized = $this->convertToJpeg($bytes);
            if ($normalized) {
                $bytes = $normalized;
                $info = @getimagesizefromstring($bytes);
            } elseif (($info[2] ?? null) !== IMAGETYPE_JPEG) {
                Log::warning('Completion report image format is unsupported', ['job_id' => $photo->job_id, 'photo_id' => $photo->id, 'mime' => $photo->mime_type]);
                return null;
            }

            if (! $info || ($info[2] ?? null) !== IMAGETYPE_JPEG) {
                return null;
            }

            return ['name' => 'Im' . $photo->id, 'bytes' => $bytes, 'width' => $info[0], 'height' => $info[1], 'orientation' => 1, 'color_space' => '/DeviceRGB'];
        } catch (\Throwable $exception) {
            Log::warning('Completion report image failed to load', ['job_id' => $photo->job_id, 'photo_id' => $photo->id, 'message' => $exception->getMessage()]);
            return null;
        }
    }

    private function convertToJpeg(string $bytes): ?string
    {
        if (! function_exists('imagecreatefromstring') || ! function_exists('imagejpeg')) {
            return null;
        }

        $image = @imagecreatefromstring($bytes);
        if (! $image) {
            return null;
        }

        $width = imagesx($image);
        $height = imagesy($image);
        $rgb = imagecreatetruecolor($width, $height);
        $white = imagecolorallocate($rgb, 255, 255, 255);
        imagefill($rgb, 0, 0, $white);
        imagecopy($rgb, $image, 0, 0, 0, 0, $width, $height);

        ob_start();
        imagejpeg($rgb, null, 90);
        $converted = ob_get_clean();
        imagedestroy($image);
        imagedestroy($rgb);

        return $converted ?: null;
    }

    private function imagePlacement(array $image, float $scale, float $x, float $y): string
    {
        $w = $image['width'] * $scale;
        $h = $image['height'] * $scale;
        return match ($image['orientation']) {
            3 => sprintf('q -%.2f 0 0 -%.2f %.2f %.2f cm /%s Do Q', $scale, $scale, $x + $w, $y + $h, $image['name']),
            6 => sprintf('q 0 -%.2f %.2f 0 %.2f %.2f cm /%s Do Q', $scale, $scale, $x, $y + $w, $image['name']),
            8 => sprintf('q 0 %.2f -%.2f 0 %.2f %.2f cm /%s Do Q', $scale, $scale, $x + $h, $y, $image['name']),
            // Keep the native pixel dimensions in the transform. The PDF
            // image object is raster data, so the scale is applied to both
            // dimensions here (this is also compatible with older readers).
            default => sprintf('q %.2f 0 0 %.2f %.2f %.2f cm /%s Do Q', $w, $h, $x, $y, $image['name']),
        };
    }

    /** Read the EXIF orientation without requiring image re-encoding. */
    private function jpegOrientation(string $bytes): int
    {
        $offset = 2;
        $length = strlen($bytes);
        while ($offset + 4 < $length && ord($bytes[$offset]) === 0xFF) {
            $marker = ord($bytes[$offset + 1]);
            $segmentLength = unpack('n', substr($bytes, $offset + 2, 2))[1] ?? 0;
            if ($marker === 0xE1 && substr($bytes, $offset + 4, 6) === "Exif\0\0") {
                $tiff = $offset + 10;
                $little = substr($bytes, $tiff, 2) === 'II';
                $u16 = fn (int $at) => $little ? unpack('v', substr($bytes, $at, 2))[1] : unpack('n', substr($bytes, $at, 2))[1];
                $u32 = fn (int $at) => $little ? unpack('V', substr($bytes, $at, 4))[1] : unpack('N', substr($bytes, $at, 4))[1];
                if ($u16($tiff + 2) === 42) {
                    $ifd = $tiff + $u32($tiff + 4);
                    $count = $u16($ifd);
                    for ($i = 0; $i < $count; $i++) {
                        $entry = $ifd + 2 + ($i * 12);
                        if ($u16($entry) === 0x0112) return max(1, min(8, (int) $u16($entry + 8)));
                    }
                }
                break;
            }
            if ($segmentLength < 2) break;
            $offset += 2 + $segmentLength;
        }
        return 1;
    }

    private function person($user): string
    {
        if (! $user) {
            return 'Unknown';
        }

        return trim(($user->name ?? 'Unknown') . ($user->email ? ' <' . $user->email . '>' : ''));
    }

    private function route(?string $label, ?string $postcode): string
    {
        return trim(($label ?: 'Not provided') . ($postcode ? ' (' . $postcode . ')' : ''));
    }

    private function date($value): string
    {
        return $value ? $value->format('d M Y H:i') : 'Not recorded';
    }

    private function label(?string $value): string
    {
        return ucwords(str_replace(['_', '-'], ' ', (string) ($value ?: 'Not recorded')));
    }

    private function text(array &$ops, string $value, float $x, float $y, float $size, bool $bold, array $rgb): void
    {
        $ops[] = sprintf(
            '%.3f %.3f %.3f rg BT /%s %.2f Tf 1 0 0 1 %.2f %.2f Tm (%s) Tj ET',
            $rgb[0], $rgb[1], $rgb[2], $bold ? 'F2' : 'F1', $size, $x, $y, $this->escape($value)
        );
    }

    private function drawRect(array &$ops, float $x, float $y, float $width, float $height, array $rgb): void
    {
        $ops[] = sprintf('q %.3f %.3f %.3f rg %.2f %.2f %.2f %.2f re f Q', $rgb[0], $rgb[1], $rgb[2], $x, $y, $width, $height);
    }

    private function drawLine(array &$ops, float $x1, float $y1, float $x2, float $y2, array $rgb, float $width): void
    {
        $ops[] = sprintf('q %.3f %.3f %.3f RG %.2f w %.2f %.2f m %.2f %.2f l S Q', $rgb[0], $rgb[1], $rgb[2], $width, $x1, $y1, $x2, $y2);
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', '(', ')', "\r", "\n"], ['\\\\', '\\(', '\\)', ' ', ' '], iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $value) ?: $value);
    }

    private function finalizePdf(array $pages): string
    {
        $objects = ["1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj", '2 0 obj << /Type /Pages /Kids [] /Count 0 >> endobj'];
        $pageIds = [];
        foreach ($pages as $page) {
            $operations = $page['operations'] ?? $page;
            $images = $page['images'] ?? [];
            $stream = implode("\n", $operations) . "\n";
            $contentId = count($objects) + 1;
            $pageId = $contentId + 1;
            $fontRegular = $pageId + 1;
            $fontBold = $pageId + 2;
            $imageIds = [];
            foreach ($images as $offset => $image) {
                $imageIds[$image['name']] = $pageId + 3 + $offset;
            }
            // PDF stream delimiters must contain real line breaks; using a
            // single-quoted PHP string here would emit the literal `\\n` and
            // make readers treat the page content as an empty stream.
            $objects[] = sprintf("%d 0 obj << /Length %d >> stream\n%sendstream endobj", $contentId, strlen($stream), $stream);
            $xObjects = '';
            foreach ($imageIds as $name => $id) {
                $xObjects .= sprintf('/%s %d 0 R ', $name, $id);
            }
            $objects[] = sprintf('%d 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 %.2f %.2f] /Contents %d 0 R /Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> /XObject << %s>> >> >> endobj', $pageId, self::WIDTH, self::HEIGHT, $contentId, $fontRegular, $fontBold, $xObjects);
            $objects[] = sprintf('%d 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj', $fontRegular);
            $objects[] = sprintf('%d 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj', $fontBold);
            foreach ($images as $image) {
                $imageId = $imageIds[$image['name']];
                // Keep the image stream declaration deliberately simple and
                // broadly compatible with Preview, WebKit and Android PDF
                // readers. Uploaded inspection photos are RGB JPEGs.
                $objects[] = sprintf("%d 0 obj << /Type /XObject /Subtype /Image /Width %d /Height %d /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length %d >> stream\n", $imageId, $image['width'], $image['height'], strlen($image['bytes'])) . $image['bytes'] . "\nendstream endobj";
            }
            $pageIds[] = $pageId;
        }
        $objects[1] = sprintf('2 0 obj << /Type /Pages /Kids [%s] /Count %d >> endobj', implode(' ', array_map(fn ($id) => $id . ' 0 R', $pageIds)), count($pageIds));

        $pdf = "%PDF-1.4\n"; $offsets = [0];
        foreach ($objects as $object) { $offsets[] = strlen($pdf); $pdf .= $object . "\n"; }
        $xref = strlen($pdf); $pdf .= "xref\n0 " . count($offsets) . "\n";
        foreach ($offsets as $offset) { $pdf .= str_pad((string) $offset, 10, '0', STR_PAD_LEFT) . " 00000 n \n"; }
        return $pdf . "trailer << /Size " . count($offsets) . " /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
    }
}
